// <auto-generated />
namespace DOCUMAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AgentMatchingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgentMatchingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202103291559438_AgentMatchingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
